### ISSUE TITLE
Problems with integer pop numbers -> floating point numbers in Python-2.7

### ISSUE THREAD

**Issue by tabbzi** [larssono/supportmix#3]
I am using SupportMix as the core part of an ancestry assignment pipeline. When making a transition from RedHat6 and RedHat7 with Python-2.7 (had other issues with Python-2.6), I've run into some issues getting SupportMix to run. I am running SupportMix directly from its uncompiled Python scripts. I am not planning to compile them into an executable at the moment.

**Here's my set up:**

OS: RedHat7
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2

-  I have `popgen.py` from `larssono/Analysis_helpers` saved in the same directory as the SupportMix scripts.
- I have also all the PyMVPA / MVPA2 modules, and the changes made to SupportMix scripts by kennedydane to import those.
- All other dependencies should be installed in their most recent versions for Python 2.7.16.

I am testing out the above setup with one chromosome from 93 ancestral populations + 1 target population phased .tped files.

**Command:**
python SupportMix --save breedcalls_SM_32 --chromosome=32 --window=80 `reference pop .tped files` `target pop .tped file`

**I receive this traceback:**

Traceback (most recent call last):
  File "_DIR_/ancestry/scripts/bin/supportmix/SupportMix", line 337, in <module>
    results=map(lambda chrom: runSVM(params, chrom), params['chrom'])
  File "_DIR_/ancestry/scripts/bin/supportmix/SupportMix", line 337, in <lambda>
    results=map(lambda chrom: runSVM(params, chrom), params['chrom'])
  File "_DIR_/ancestry/scripts/bin/supportmix/SupportMix", line 153, in runSVM
    admixedClass, p=smoother(mapLocations, ancestralSuccess, admixedClassPre)
  File "_DIR_/ancestry/scripts/bin/supportmix/regionClassifier.py", line 136, in __call__
    model.forward_backward(admixedClass[:,i])
  File "_DIR_/ancestry/scripts/bin/supportmix/hmm.py", line 82, in forward_backward
    alpha[0,:]=b[0,:,obs[0]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**When I step through with `pdb` debugging starting from line 337 to see what is fed to model.forward_backward(admixedClass[:,i]), I find this:**

(Pdb) l
112  	                elif snpInfo[0]>chrom: fileDone=True; break  #Finnished when read past chrom
113  	                elif snpInfo[0]==chrom:
114  	                    snpNames.append(snpInfo[1])
115  	                    mapLocations.append(float(snpInfo[2]))
116  	                    snpLocations.append(float(snpInfo[3]))
117  ->	                    vals.append(fileReader.nucleotides2Haplotypes(sum(snps, []), False))
118  	        vals=np.asarray(vals).T
119  	        if len(vals)==0: break #No SNPs in window
120  	        ancestral, admixed=classifier(vals[:nTrain], labelsTrain, vals[-nTest:])
121  	        ancestralSuccess.append(ancestral)
122  	        admixedClass.append(admixed)
(Pdb) print(admixedClass)
[[17.0, 17.0, 10.0, 14.0, 5.0, 19.0, 19.0, 7.0, 16.0, 16.0, 9.0, 8.0, 29.0, 26.0, 9.0, 9.0, 14.0, 23.0], [12.0, 17.0, 6.0, 18.0, 11.0, 10.0, 19.0, 19.0, 29.0, 7.0, 32.0, 3.0, 29.0, 26.0, 8.0, 14.0, 7.0, 1.0], [17.0, 22.0, 10.0, 16.0, 11.0, 22.0, 19.0, 19.0, 22.0, 19.0, 15.0, 22.0, 16.0, 26.0, 11.0, 20.0, 17.0, 12.0]]

Well, those are floating points.

**I am not sure why, but when I reduce the number of populations supplied to say, 60, I get this traceback:**

Traceback (most recent call last):
  File "_DIR_/ancestry/scripts/bin/supportmix/SupportMix", line 340, in <module>
    results=map(lambda chrom: runSVM(params, chrom), params['chrom'])
  File "_DIR_/ancestry/scripts/bin/supportmix/SupportMix", line 340, in <lambda>
    results=map(lambda chrom: runSVM(params, chrom), params['chrom'])
  File "_DIR_/ancestry/scripts/bin/supportmix/SupportMix", line 117, in runSVM
    vals.append(fileReader.nucleotides2Haplotypes(sum(snps, []), False))
  File "_DIR_/ancestry/scripts/bin/supportmix/popgen.py", line 46, in nucleotides2Haplotypes
    majorAllele=findAlleles(pop, warnings)[0]
  File "_DIR_/ancestry/scripts/bin/supportmix/popgen.py", line 116, in findAlleles
    return alleles[idx], 'Q'
TypeError: only integer scalar arrays can be converted to a scalar index

But it is similar: an error coming from runSVM where indices aren't being supplied in the proper way / as integers.

Any suggestions or ideas for resolving this are much appreciated! Thank you.

**Comment by tabbzi** [comment]
I [made a fork](https://github.com/tabbzi/supportmix) and added some changes to try to keep integer arrays as integers, and SupportMix seems to be working now. The output files for the chromosome I tested are generated. I'm testing it out with our ancestry assignment scripts and panel to see if it gives the same output as our old setup.

When I know that the changes work, I'll do a pull request for more feedback. Not sure whether the changes are too specific to my set up with RH7 + Python-2.7, though.

My concern is that there were a few RunTime Warnings in the Hidden Markov Model:

./ancestry/git/supportmix/hmm.py:99: RuntimeWarning: overflow encountered in divide
  alpha[tf,:]/=RENORM
./ancestry/git/supportmix/hmm.py:96: RuntimeWarning: invalid value encountered in double_scalars
  alpha[tf,j]+=alpha[tf-1,i]*af[i,j]*bf[j, obs[tf]]    #forward
./ancestry/git/supportmix/hmm.py:106: RuntimeWarning: invalid value encountered in divide
  self.pstate=((alpha*beta).T/self.lhood).T

Should these be concerning?

**Comment by tabbzi** [comment]
Found reason why those RunTime Warnings should be concerning: they’re introducing `nan` probabilities, which my outputs from SupportMix in the past have never given.

**Comment by tabbzi** [comment]
I believe this is occurring in the `model.forward_backward` when called in `regionClassifier.py`. I introduced `.astype(int)` to `admixedClass[:,i]`, which I think is the right decision as it is an array of population numbers. Otherwise, I get an indexing error from `model.forward_backward(admixedClass[:,i])` and `hmm.py` (`IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices`). I need to see how that introduces `nan` downstream, within the `model.forward_backward` function.

**Comment by tabbzi** [comment]
I don't think the `.astype(int)` introduced the problem, but rather allowed the script to proceed and reveal the `nan` issue.

I am guessing that the `nan` values are introduced from division by some small number that converted to 0. I would think that these lines in `hmm.py` were intended to resolve that problem:

`RENORM=1e-17`

`if alpha[tf,:].sum() < RENORM:`
`           alpha[tf,:]/=RENORM`
`if beta[tb,:].sum() < RENORM:`
`           beta[tb,:]/=RENORM`
I assume this is supposed to use 1e-17 instead of any value that's _really_ small, so that `nan` doesn’t occur in division
(but it’s still occurring in division -- maybe `numpy` can't store some floats smaller than 1e-17 so the comparison to 1e-17 fails here)

**Comment by tabbzi** [comment]
BTW, the final probabilities using the default transition and emission matrix and observations for `hmm.py` included in `if __name__ == '__main__':`, when I just run `python hmm.py`, are:

[[0.69408617 0.         0.         0.24882465 0.05708918]
 [0.13829464 0.         0.         0.83042452 0.03128084]
 [0.46154292 0.         0.         0.48958771 0.04886938]
 ...
 [0.36914316 0.         0.         0.58278314 0.0480737 ]
 [0.28502931 0.         0.         0.66417557 0.05079512]
 [0.40872343 0.         0.         0.51283493 0.07844165]]

Do these appear roughly correct?

I am finding that during the `forward_backward` function, the alpha for some ancestral populations will contain `-inf` and `nan` entries. It's not consistent to any one population when I shuffle the order of populations fed to SupportMix. It is not due to `RENORM`, as the `alpha` already contains `nan` and/or `-inf` at that point.

**Comment by tabbzi** [comment]
From what I've gathered, it appears the transition matrix `a` -- for which, by definition*, all elements should be negative -- ends up containing at least one negative number. This negative number proliferates itself and becomes continually larger & larger in magnitude during the forward operation, until it cannot be stored, reverts to `nan`, and yields the RunTime Warning.

Perhaps some newer behavior in numpy. I am going to look closer at this part of `regionClassifier.py` where the `a` transition matrix gets generated:

#determine transition matrices
        a=[]; b=[]
        oldPos=0
        for i in range(0,len(mapLocations), win_size):
            newPos=np.mean(mapLocations[i:i+win_size])
            dM=-(newPos - oldPos)/100*self.nGens
            e=np.exp(dM)
            oldPos=newPos
            x=np.empty((self.nClasses, self.nClasses)) #Create state transitions
            for j in range(self.nClasses):
                x[j,:]=(1.-e)/(self.nClasses-1) # this can definitely lead to negatives if e > 1
                x[j,j]=e
            a.append(x)
        a=np.asarray(a)

\* but totally possible, it seems [according to this stack?](https://stackoverflow.com/questions/35463433/python-hmmlearn-negative-transmat)

**Comment by tabbzi** [comment]
Here's a two possibilities that I am considering: 

[negative zeroes might introduce odd behavior](https://stackoverflow.com/questions/4083401/negative-zero-in-python)

[np.empty introduces random floats, some negative, that might not be getting replaced in the transition matrix fill loop](https://stackoverflow.com/questions/44875242/numpy-empty-giving-nonempty-array)

**Comment by tabbzi** [comment]
Ruled out both of those possibilities. The x = np.empty gets successfully filled by the loop. However, I noticed that the `mapLocations` array is out of order (despite cM locations being in order within the .tped files). Since that is used for indexing the loop that fills `x`, perhaps that introduces issues?

ie. `mapLocations` may print as
[26.02, 29.05, 32.33, 45.23,  **50.8685, 0.01**, 1.34, …]
instead of
[0.01, 1.34, 5.23, …, 26.02, 29.05, 32.33, 45.23, 50.8685, …]

The way I expect this would cause issues is between the `newPos` and `oldPos` when the new position suddenly changes from being greater than the old position to less than. `e` in `x[j,:]=(1.-e)/(self.nClasses-1)` may end up being greater than 1.

**Comment by tabbzi** [comment]
Adding a `mapLocations.sort()` before the loop seems to resolve the issue, so I probably had a problem with the tped cMs

**Comment by tabbzi** [comment]
Corrected the reference population .tped cMs; however, another problem that didn’t seem to be a problem before: sometimes, the final marker count in the query admixed .tped is fewer than the reference .tpeds used as ancestral pops in SupportMix (138,422 instead of 148,229; this is expected as intersecting sequencing genotypes and array genotypes). Presumably, this has been handled by SupportMix, as never seemed to present an issue before. But now, it throws off the mapLocations as the scripts uses markers that aren’t in common between the query admixed .tped and the reference .tpeds. I think the function `concurrentFileReader` was meant to handle this?
